const base='reedah-emporiumextracted2/images/';const shadeImages={Clear:base+'lip-gloss-clear.jpg',Nude:base+'lip-gloss-nude.jpg',Brown:base+'lip-gloss-brown.jpg',Pink:base+'lip-gloss-pink.jpg',Berry:base+'lip-gloss-berry.jpg'};let selectedShade='Clear',productQty=1,cart=[];const naira=n=>`₦${n.toLocaleString()}`;
function selectShade(shade){selectedShade=shade;document.getElementById('selectedShade').textContent=shade;document.getElementById('shadeImage').src=shadeImages[shade];document.querySelectorAll('.thumb').forEach((b,i)=>b.classList.toggle('active',i===Object.keys(shadeImages).indexOf(shade)));document.querySelectorAll('.shade-dot').forEach(b=>b.classList.toggle('active',b.textContent.trim().startsWith(shade)))}
function changeQty(amount){productQty=Math.max(1,productQty+amount);document.getElementById('productQty').textContent=productQty}
function addGlossToCart(){for(let i=0;i<productQty;i++)addItem({name:"Reedah's Lip Gloss",price:3000,desc:'High shine. Non-sticky. Long lasting.',shade:selectedShade})}
function addItem(p){const key=p.name+(p.shade||'');const existing=cart.find(x=>x.key===key);if(existing)existing.qty++;else cart.push({...p,key,qty:1});renderCart();openCart()}
function renderCart(){document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);document.getElementById('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div><strong>${x.name}</strong>${x.shade?`<small>Shade: ${x.shade}</small>`:''}<small>Qty: ${x.qty}</small></div><div>${naira(x.price*x.qty)}<br><button onclick="removeItem(${i})" style="border:0;background:none;color:#d94c77;cursor:pointer">Remove</button></div></div>`).join(''):'<p style="color:#777;padding:30px 0">Your bag is empty.</p>';document.getElementById('cartTotal').textContent=naira(cart.reduce((s,x)=>s+x.price*x.qty,0))}
function removeItem(i){cart.splice(i,1);renderCart()}function openCart(){document.getElementById('cart').classList.add('open');document.getElementById('overlay').classList.add('open')}function closeCart(){document.getElementById('cart').classList.remove('open');document.getElementById('overlay').classList.remove('open')}
function checkout(){if(!cart.length)return;document.getElementById('checkoutTotal').textContent=naira(cart.reduce((s,x)=>s+x.price*x.qty,0));document.getElementById('checkoutModal').classList.add('open')}
function closeCheckout(){document.getElementById('checkoutModal').classList.remove('open')}function toggleAddress(){document.getElementById('addressWrap').style.display=document.getElementById('fulfilment').value==='Delivery'?'grid':'none'}
function sendOrderToWhatsApp(){const name=document.getElementById('customerName').value.trim(),phone=document.getElementById('customerPhone').value.trim(),fulfilment=document.getElementById('fulfilment').value,address=document.getElementById('customerAddress').value.trim(),time=document.getElementById('orderTime').value.trim(),payment=document.getElementById('payment').value;if(!name||!phone){alert('Please enter your name and phone number.');return}if(fulfilment==='Delivery'&&!address){alert('Please enter your delivery address.');return}const lines=cart.map(x=>`• ${x.qty} × ${x.name}${x.shade?` — Shade: ${x.shade}`:''} — ${naira(x.price*x.qty)}`).join('\n'),total=naira(cart.reduce((s,x)=>s+x.price*x.qty,0));const msg=`Hi Reedah's! 💕\n\nI'd like to place an order.\n\nORDER\n${lines}\n\nTotal: ${total}\n\nCUSTOMER DETAILS\nName: ${name}\nPhone: ${phone}\nFulfilment: ${fulfilment}\n${fulfilment==='Delivery'?`Address: ${address}\n`:''}Preferred time: ${time||'Not specified'}\nPayment: ${payment}\n\nPlease confirm my order and the next steps. Thank you!`;window.location.href=`https://wa.me/2348121757186?text=${encodeURIComponent(msg)}`}
renderCart();toggleAddress();